"""create phases and weeks tables

Revision ID: 0a0c8834ce3f
Revises: 
Create Date: 2026-07-10 13:17:44.641245
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0c8834ce3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phases_key'), 'phases', ['key'], unique=True)
    op.create_table('weeks',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=300), nullable=False),
    sa.Column('resources', sa.Text(), nullable=False),
    sa.Column('deliverable', sa.Text(), nullable=False),
    sa.Column('hours_min', sa.Float(), nullable=False),
    sa.Column('hours_max', sa.Float(), nullable=False),
    sa.Column('buffer', sa.Boolean(), nullable=False),
    sa.Column('week_label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'late', 'skipped', name='week_status', native_enum=False, length=20), nullable=False),
    sa.Column('actual_hours', sa.Float(), nullable=False),
    sa.Column('recap_sunday', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_weeks_phase_id'), 'weeks', ['phase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeks_phase_id'), table_name='weeks')
    op.drop_table('weeks')
    op.drop_index(op.f('ix_phases_key'), table_name='phases')
    op.drop_table('phases')
    # ### end Alembic commands ###