"""create github_events and sync_state

Revision ID: 31ced39ea5a6
Revises: ea837a767e64
Create Date: 2026-07-10 18:41:18.959345
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ced39ea5a6'
down_revision: Union[str, Sequence[str], None] = 'ea837a767e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('commit', 'pr', name='github_event_kind', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_events_authored_at'), 'github_events', ['authored_at'], unique=False)
    op.create_index(op.f('ix_github_events_repo'), 'github_events', ['repo'], unique=False)
    op.create_index('ix_github_events_repo_sha', 'github_events', ['repo', 'sha'], unique=True)
    op.create_table('github_sync_state',
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('last_sha', sa.String(length=40), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('repo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_sync_state')
    op.drop_index('ix_github_events_repo_sha', table_name='github_events')
    op.drop_index(op.f('ix_github_events_repo'), table_name='github_events')
    op.drop_index(op.f('ix_github_events_authored_at'), table_name='github_events')
    op.drop_table('github_events')
    # ### end Alembic commands ###