"""create sessions table

Revision ID: 5845a03ee9f7
Revises: 6b943e3771b2
Create Date: 2026-07-10 14:41:48.633501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5845a03ee9f7'
down_revision: Union[str, Sequence[str], None] = '6b943e3771b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('focus', 'pomodoro', name='session_type', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_week_id'), 'sessions', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_week_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###