"""create users and app_settings tables

Revision ID: 6b943e3771b2
Revises: 0a0c8834ce3f
Create Date: 2026-07-10 13:52:40.740027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b943e3771b2'
down_revision: Union[str, Sequence[str], None] = '0a0c8834ce3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('tracked_repos', sa.JSON(), nullable=False),
    sa.Column('pomo_work_min', sa.Integer(), nullable=False),
    sa.Column('pomo_short_break_min', sa.Integer(), nullable=False),
    sa.Column('pomo_long_break_min', sa.Integer(), nullable=False),
    sa.Column('pomo_marathon_break_min', sa.Integer(), nullable=False),
    sa.Column('pomo_cycles_per_short_set', sa.Integer(), nullable=False),
    sa.Column('pomo_cycles_per_long_break', sa.Integer(), nullable=False),
    sa.Column('weekly_target_min', sa.Integer(), nullable=False),
    sa.Column('weekly_target_max', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='single_row_settings'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('app_settings')
    # ### end Alembic commands ###