"""create daily_logs and recaps tables

Revision ID: ea837a767e64
Revises: dc29a2c21286
Create Date: 2026-07-10 17:52:42.438832
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea837a767e64'
down_revision: Union[str, Sequence[str], None] = 'dc29a2c21286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('learned', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('hours_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_id', 'log_date', name='uq_daily_week_date')
    )
    op.create_index(op.f('ix_daily_logs_log_date'), 'daily_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_daily_logs_week_id'), 'daily_logs', ['week_id'], unique=False)
    op.create_table('recaps',
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(length=40), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('week_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recaps')
    op.drop_index(op.f('ix_daily_logs_week_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_log_date'), table_name='daily_logs')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###